// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
	"fmt"
	"os"

	"github.com/mailru/easyjson/gen"

	pkg "github.com/robfordww/runxml/generator_test"
)

func main() {
	g := gen.NewGenerator("logitems_easyjson.go")
	g.SetPkg("runxml", "github.com/robfordww/runxml/generator_test")
	g.Add(pkg.EasyJSON_exporter_Logitem(nil))
	if err := g.Run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
